# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddcommon"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]
bench =false

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
static_assertions = "1.1.0"
libc = "0.2"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_System_Performance",
]

[dev-dependencies]
indexmap = "2.2"
maplit = "1.0"

